// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/listings": {
            "get": {
                "description": "Returns every available listing",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Listings"
                ],
                "summary": "Get all listings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_models_response.GetListingsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_models.HTTPError"
                        }
                    }
                }
            }
        },
        "/tours": {
            "post": {
                "description": "Creates a new onboarding tour draft",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tours"
                ],
                "summary": "Create a new tour",
                "parameters": [
                    {
                        "description": "Tour object",
                        "name": "tour",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_domains.Tour"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_models.HTTPError"
                        }
                    }
                }
            }
        },
        "/tours/published": {
            "get": {
                "description": "Returns published tours with their hints for a specific target path",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tours"
                ],
                "summary": "Get published tours by path",
                "parameters": [
                    {
                        "type": "string",
                        "example": "/dashboard",
                        "description": "Target path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Vanady39_cluer_internal_domains.Tour"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_models.HTTPError"
                        }
                    }
                }
            }
        },
        "/tours/{tourId}/hints": {
            "post": {
                "description": "Creates a new hint for a specific tour",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hints"
                ],
                "summary": "Create a hint for a tour",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Tour ID",
                        "name": "tourId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Hint object",
                        "name": "hint",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_domains.Hint"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_models.HTTPError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_models.HTTPError"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "description": "Returns the currently authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get the current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_models_response.GetCurrentUserResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_models.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Vanady39_cluer_internal_domains.Audience": {
            "type": "object",
            "properties": {
                "max_shows": {
                    "type": "integer"
                },
                "only_new": {
                    "type": "boolean"
                },
                "show_once": {
                    "type": "boolean"
                }
            }
        },
        "github_com_Vanady39_cluer_internal_domains.Hint": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Здесь вы можете изменить параметры аккаунта"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-08-05T12:00:00Z"
                },
                "expected_input": {
                    "type": "string",
                    "example": "John Doe"
                },
                "id": {
                    "type": "string",
                    "example": "01914f6a-8c9b-7a0b-9b0b-8c9b7a0b9b0c"
                },
                "input_placeholder": {
                    "type": "string",
                    "example": "Введите ваше имя"
                },
                "media_url": {
                    "type": "string",
                    "example": "https://cdn.example.com/onboarding/settings.mp4"
                },
                "placement": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_domains.Placement"
                        }
                    ],
                    "example": "bottom"
                },
                "required": {
                    "type": "boolean",
                    "example": false
                },
                "selector": {
                    "type": "string",
                    "example": "#settings-btn"
                },
                "spotlight": {
                    "type": "boolean",
                    "example": true
                },
                "step": {
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "Нажмите кнопку настроек"
                },
                "tour_id": {
                    "type": "string",
                    "example": "01914f6a-8c9b-7a0b-9b0b-8c9b7a0b9b0b"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-08-05T12:00:00Z"
                },
                "wait_for_selector": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_Vanady39_cluer_internal_domains.Placement": {
            "type": "string",
            "enum": [
                "top",
                "bottom",
                "center",
                "left-top",
                "right-top",
                "left",
                "right"
            ],
            "x-enum-varnames": [
                "PlacementTop",
                "PlacementBottom",
                "PlacementCenter",
                "PlacementLeftTop",
                "PlacementRightTop",
                "PlacementLeft",
                "PlacementRight"
            ]
        },
        "github_com_Vanady39_cluer_internal_domains.Tour": {
            "type": "object",
            "properties": {
                "audience": {
                    "$ref": "#/definitions/github_com_Vanady39_cluer_internal_domains.Audience"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-08-05T12:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Тур по основным функциям дашборда"
                },
                "hints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Vanady39_cluer_internal_domains.Hint"
                    }
                },
                "id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "01914f6a-8c9b-7a0b-9b0b-8c9b7a0b9b0b"
                },
                "priority": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_domains.TourStatus"
                        }
                    ],
                    "example": "draft"
                },
                "target_path": {
                    "type": "string",
                    "example": "/dashboard"
                },
                "title": {
                    "type": "string",
                    "example": "Добро пожаловать в систему"
                },
                "trigger_type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Vanady39_cluer_internal_domains.TriggerType"
                        }
                    ],
                    "example": "on_load"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-08-05T12:00:00Z"
                }
            }
        },
        "github_com_Vanady39_cluer_internal_domains.TourStatus": {
            "type": "string",
            "enum": [
                "draft",
                "published",
                "archived"
            ],
            "x-enum-varnames": [
                "TourDraft",
                "TourPublished",
                "TourArchived"
            ]
        },
        "github_com_Vanady39_cluer_internal_domains.TriggerType": {
            "type": "string",
            "enum": [
                "on_load",
                "delay",
                "exit_intent",
                "manual"
            ],
            "x-enum-varnames": [
                "TriggerOnLoad",
                "TriggerDelay",
                "TriggerExitIntent",
                "TriggerManual"
            ]
        },
        "github_com_Vanady39_cluer_internal_models.HTTPError": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Shorthand error",
                    "type": "string"
                },
                "message": {
                    "description": "Pretty error message",
                    "type": "string"
                }
            }
        },
        "github_com_Vanady39_cluer_internal_models_response.GetCurrentUserResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_Vanady39_cluer_internal_models_response.User"
                }
            }
        },
        "github_com_Vanady39_cluer_internal_models_response.GetListingsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Vanady39_cluer_internal_models_response.Listing"
                    }
                }
            }
        },
        "github_com_Vanady39_cluer_internal_models_response.Listing": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imageUrl": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_Vanady39_cluer_internal_models_response.User": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Cluer",
	Description:      "Onboarding tours and listings API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
